// AUTO-GENERATED by export.py — do not edit by hand.
// Regenerated after every transaction so the dashboard stays current.
window.EXPENSE_DATA = [
  {
    "id": 1,
    "date": "2026-07-01",
    "category": "travel",
    "amount": 500.0,
    "note": "ola",
    "type": "expense"
  }
];

window.EXPENSE_CONFIG = {
  "currency": "₹",
  "monthlyBudget": 40000,
  "budgets": {
    "travel": 3000,
    "food": 6000,
    "groceries": 5000,
    "clothes": 2500,
    "rent": 15000,
    "bills": 4000,
    "luxuries": 2000,
    "investments": 8000,
    "health": 2000,
    "education": 2000,
    "other": 1500
  },
  "categories": [
    "travel",
    "food",
    "groceries",
    "clothes",
    "rent",
    "bills",
    "luxuries",
    "investments",
    "health",
    "education",
    "other"
  ]
};
