"""
export.py
---------
Reads every transaction from MySQL plus the budgets from config.json, and
writes data.js next to dashboard.html:

    window.EXPENSE_DATA = [ {id, date, category, amount, note, type}, ... ];
    window.EXPENSE_CONFIG = { currency, monthlyBudget, budgets, categories };

dashboard.html loads this via <script src="data.js"></script> (NOT fetch),
so the dashboard works straight off disk with file:// and zero server.

IMPORTANT: the Telegram bot token is intentionally NEVER written into this
file — only currency/budget/category settings are exposed to the browser.

Run standalone any time with:  python export.py
The bot also calls export_data() after every message so the dashboard is
always current.
"""

import json
import db

DATA_JS_PATH = "data.js"
CONFIG_PATH = "config.json"


def _load_public_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    # Only pass along browser-safe fields — never the telegram token or
    # mysql credentials.
    return {
        "currency": cfg.get("currency", "₹"),
        "monthlyBudget": cfg.get("monthlyBudget", 0),
        "budgets": cfg.get("budgets", {}),
        "categories": list(cfg.get("budgets", {}).keys()),
    }


def export_data(out_path=DATA_JS_PATH):
    rows = db.all_rows()

    # serialize rows -> JSON-friendly dicts (dates/decimals need string/float conversion)
    serialized = []
    for r in rows:
        serialized.append({
            "id": r["id"],
            "date": r["date"].isoformat() if hasattr(r["date"], "isoformat") else str(r["date"]),
            "category": r["category"],
            "amount": float(r["amount"]),
            "note": r["note"] or "",
            "type": r["type"],
        })

    public_config = _load_public_config()

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by export.py — do not edit by hand.\n")
        f.write("// Regenerated after every transaction so the dashboard stays current.\n")
        f.write("window.EXPENSE_DATA = ")
        json.dump(serialized, f, ensure_ascii=False, indent=2)
        f.write(";\n\n")
        f.write("window.EXPENSE_CONFIG = ")
        json.dump(public_config, f, ensure_ascii=False, indent=2)
        f.write(";\n")

    return out_path, len(serialized)


if __name__ == "__main__":
    path, count = export_data()
    print(f"Wrote {count} transactions to {path}")
